### PR TITLE
Corrected typo in description of pr2 effort controllers.

### PR DESCRIPTION
**Pull request by airballking**

### CODE REVIEW

**Comment by trainman419** [comment]
I'm worried that this typo may be present and depended on elsewhere; perhaps in the URDF or other controller configurations. Can you confirm or deny?

**Comment by airballking** [comment]
I ran 
  grep -r "shouler_pan" *
under /opt/ros/groovy and /opt/ros/hydro on the PR2 in our lab. 

For Hydro, there were no other hits for this typo than in this file. Under Groovy, the exact same typo was found in the equivalent file in pr2_controller_configuration_gazebo. I opened a pull request with a correction there, too: pr2/pr2_simulator#103 

Additionally, this particular typo renders the controller configuration useless --the controller manager throws an error when loading it. Hence, I would be very surprised if any working functionality is depending on this typo.

**Comment by trainman419** [comment]
Thanks!

**Comment by airballking** [comment]
You're welcome.

**Pull request merged**
