### PR TITLE
python3 transition

### PR DESCRIPTION
**Pull request by v4hn**
There's probably more to transition, but I tested on real hardware. :dog: 

@k-okada I created a new noetic-devel branch because I did not bother with python2/python3 compatibility.
This should be released into noetic with the changes I guess

### CODE REVIEW

**Comment by davefeilseifer** [comment]
I happy to do the merge, but what's happening with the build error @v4hn ?

**Comment by v4hn** [comment]
looks like the build farm scripts are actually broken on python3.6, at least without changes from earlier versions? I've not seen that before, but I also didn't have much chance to yet.
@k-okada any idea?
I believe this patch should be safe to merge for now, this is a new branch and improves support for noetic.

**Comment by k-okada** [comment]
@v4hn @davefeilseifer thanks for comment, i have created PR (https://github.com/PR2/pr2_robot/pull/272) to fix CI as well as python2/python3 check. 
I personally prefer to use single branch for support both python2/python3, because I do not want to keep update multiple branches.

**Comment by v4hn** [comment]
closed in favor of #272

**Pull request closed without merging**
